function [fitResult, gof] = createFit(xData, yData, dependent, modelFunction, independent, optionalStartValues)
%CREATEFIT(TIMESTAMPS,DISTANCES)
%  Create a fit.
%
%  Data for 'sqFun' fit:
%      X Input : timeStamps
%      Y Output: displacement (angular/linear)
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%

%  Auto-generated by MATLAB on 23-Feb-2016 16:33:50


%% Fit: 'sqFun'.
[xData, yData] = prepareCurveData( xData, yData );

% Set up fittype and options.
ft = fittype( modelFunction , 'independent', independent, 'dependent', dependent );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
if exist('optionalStartValues')
    opts.StartPoint = optionalStartValues;
end
% Fit model to data.
warning off;
[fitResult, gof] = fit( xData, yData, ft, opts );
warning on;

